### ISSUE TITLE
Making the App Responsive and Look Good on Mobile Devices

### ISSUE THREAD

**Issue by MarcoMorawec** [tpetrini/Splur#1]
On mobile things don't look as good as they could be.

One thing you could look into is to add the "mobile meta tag" to your app, so the responsive effect of Bootstrap actually shows up on Mobile.

Let me know in the comments once you figured that step out :)

**Comment by atxnow** [comment]
Hey, I figured out how to integrate the mobile meta tag.  Looks much better!

**Comment by MarcoMorawec** [comment]
@tpetrini :+1: 

Looks like you fixed it right with this [commit](https://github.com/tpetrini/Splur/commit/531a15bfdee194883d1da062685a890e63e984f0)

Make sure you close the issue, now that you solved it.

Side note: try to always reference your code and/or the specific commits in any of the comments, since it will make the communication a lot more precise.
