### ISSUE TITLE
Fixing the Top-Nav

### ISSUE THREAD

**Issue by MarcoMorawec** [tpetrini/Splur#2]
The "contribute" and "about" links in the top-nav are not aligning properly to the right hand side.

Can you align them according to the wireframes? 

Doing so should also take care of the tagline, which is flush against the top of the screen.

Right now, I'm seeing this:

![screen shot 2015-05-17 at 9 01 53 pm](https://cloud.githubusercontent.com/assets/1474717/7673042/3355b628-fcd8-11e4-959b-bde620578892.png)

**Comment by atxnow** [comment]
Hi!  I aligned the contribute and about links, then moved the tagline off the top of the screen.  I checked it out on my mobile too

**Comment by MarcoMorawec** [comment]
@tpetrini :+1: 

Make sure you close the issue :)

**Comment by atxnow** [comment]
Awesome!  Closing the issue out.
