### ISSUE TITLE
Adjust the Font Color in the Logo 

### ISSUE THREAD

**Issue by MarcoMorawec** [tpetrini/Splur#3]
This is a really small details - but here we go.

The blue font of the logo clashes visually with the red circle. Things would look a lot better if the text would be white or black.

Here's what I see:

![screen shot 2015-05-17 at 9 01 53 pm](https://cloud.githubusercontent.com/assets/1474717/7673057/94a43c4c-fcd8-11e4-8083-71b7426ac19e.png)

**Comment by atxnow** [comment]
And.... got rid of the blue!!!  Fun exercise :)

**Comment by MarcoMorawec** [comment]
@tpetrini :+1: 

Make sure you close the issue :)

**Comment by atxnow** [comment]
Nice!  Thanks!
